version = 1

[envs.git]
channels = ["conda-forge"]
dependencies = { git = "*" }
exposed = { git = "git", git-cvsserver = "git-cvsserver", git-receive-pack = "git-receive-pack", git-shell = "git-shell", git-upload-archive = "git-upload-archive", git-upload-pack = "git-upload-pack", gitk = "gitk", scalar = "scalar" }

[envs.stow]
channels = ["conda-forge"]
dependencies = { stow = "*" }
exposed = { chkstow = "chkstow", stow = "stow" }

[envs.git-lfs]
channels = ["conda-forge"]
dependencies = { git-lfs = "*" }
exposed = { git-lfs = "git-lfs" }

[envs.unzip]
channels = ["conda-forge"]
dependencies = { unzip = "*" }
exposed = { funzip = "funzip", unzip = "unzip", unzipsfx = "unzipsfx", zipgrep = "zipgrep", zipinfo = "zipinfo" }

[envs.atool]
channels = ["conda-forge"]
dependencies = { atool = "*" }
exposed = { acat = "acat", adiff = "adiff", als = "als", apack = "apack", arepack = "arepack", atool = "atool", aunpack = "aunpack" }

[envs.pdfgrep]
channels = ["conda-forge"]
dependencies = { pdfgrep = "*" }
exposed = { pdfgrep = "pdfgrep" }

[envs.ripgrep]
channels = ["conda-forge"]
dependencies = { ripgrep = "*" }
exposed = { rg = "rg" }

[envs.fzf]
channels = ["conda-forge"]
dependencies = { fzf = "*" }
exposed = { fzf = "fzf" }

[envs.libtree]
channels = ["conda-forge"]
dependencies = { libtree = "*" }
exposed = { libtree = "libtree" }

[envs.fd-find]
channels = ["conda-forge"]
dependencies = { fd-find = "*" }
exposed = { fd = "fd" }

[envs.difftastic]
channels = ["conda-forge"]
dependencies = { difftastic = "*" }
exposed = { difft = "difft" }

[envs.mold]
channels = ["conda-forge"]
dependencies = { mold = "*" }
exposed = { "ld.mold" = "ld.mold", mold = "mold" }

[envs.ccache]
channels = ["conda-forge"]
dependencies = { ccache = "*" }
exposed = { ccache = "ccache" }

[envs.ninja]
channels = ["conda-forge"]
dependencies = { ninja = "*" }
exposed = { ninja = "ninja" }

[envs.bat]
channels = ["conda-forge"]
dependencies = { bat = "*" }
exposed = { bat = "bat" }

[envs.taplo]
channels = ["conda-forge"]
dependencies = { taplo = "*" }
exposed = { taplo = "taplo" }

[envs.stylua]
channels = ["conda-forge"]
dependencies = { stylua = "*" }
exposed = { stylua = "stylua" }

[envs.actionlint]
channels = ["conda-forge"]
dependencies = { actionlint = "*" }
exposed = { actionlint = "actionlint" }

[envs.rattler-build]
channels = ["conda-forge"]
dependencies = { rattler-build = "*" }
exposed = { rattler-build = "rattler-build" }

[envs.gh]
channels = ["conda-forge"]
dependencies = { gh = "*" }
exposed = { gh = "gh" }

[envs.less]
channels = ["conda-forge"]
dependencies = { less = "*" }
exposed = { less = "less", lessecho = "lessecho", lesskey = "lesskey" }

[envs.nvim]
channels = ["conda-forge"]
dependencies = { nvim = "*" }
exposed = { nvim = "nvim" }

[envs.openssh]
channels = ["conda-forge"]
dependencies = { openssh = "*" }
exposed = { scp = "scp", sftp = "sftp", ssh = "ssh", ssh-add = "ssh-add", ssh-agent = "ssh-agent", ssh-keygen = "ssh-keygen", ssh-keyscan = "ssh-keyscan", sshd = "sshd" }

[envs.nvitop]
channels = ["conda-forge"]
dependencies = { nvitop = "*" }
exposed = { nvitop = "nvitop", nvisel = "nvisel" }

[envs.tmux]
channels = ["conda-forge"]
dependencies = { tmux = "*" }
exposed = { tmux = "tmux" }

[envs.mosh]
channels = ["conda-forge"]
dependencies = { mosh = "*" }
exposed = { mosh = "mosh", mosh-client = "mosh-client", mosh-server = "mosh-server" }

[envs.platformio]
channels = ["conda-forge"]
dependencies = { platformio = "*" }
exposed = { platformio = "platformio", pio = "pio", piodebuggdb = "piodebuggdb" }

[envs.screen]
channels = ["conda-forge"]
dependencies = { screen = "*" }
exposed = { screen = "screen", "screen-4.8.0" = "screen-4.8.0" }

[envs.yt-dlp]
channels = ["conda-forge"]
dependencies = { yt-dlp = "*" }
exposed = { yt-dlp = "yt-dlp" }

[envs.lldb]
channels = ["conda-forge"]
dependencies = { lldb = "*" }
exposed = { lldb = "lldb", lldb-argdumper = "lldb-argdumper", lldb-dap = "lldb-dap", lldb-instr = "lldb-instr", lldb-server = "lldb-server" }

[envs.gdb]
channels = ["conda-forge"]
dependencies = { gdb = "*" }
exposed = { ".gdb-post-link" = ".gdb-post-link", gcore = "gcore", gdb = "gdb", gdb-add-index = "gdb-add-index", gdbserver = "gdbserver", gstack = "gstack" }

[envs.valgrind]
channels = ["conda-forge"]
dependencies = { valgrind = "*" }
exposed = { callgrind_annotate = "callgrind_annotate", callgrind_control = "callgrind_control", cg_annotate = "cg_annotate", cg_diff = "cg_diff", cg_merge = "cg_merge", ms_print = "ms_print", valgrind = "valgrind", valgrind-di-server = "valgrind-di-server", valgrind-listener = "valgrind-listener", vgdb = "vgdb" }

[envs.iperf]
channels = ["conda-forge"]
dependencies = { iperf = "*" }
exposed = { iperf3 = "iperf3" }

[envs.xclip]
channels = ["conda-forge"]
dependencies = { xclip = "*" }
exposed = { xclip = "xclip", xclip-copyfile = "xclip-copyfile", xclip-cutfile = "xclip-cutfile", xclip-pastefile = "xclip-pastefile" }

[envs.fish]
channels = ["conda-forge"]
dependencies = { fish = "*" }
exposed = { fish = "fish", fish_indent = "fish_indent", fish_key_reader = "fish_key_reader" }

[envs.luarocks]
channels = ["conda-forge"]
dependencies = { luarocks = "*" }
exposed = { luarocks = "luarocks", luarocks-admin = "luarocks-admin" }

[envs.jless]
channels = ["conda-forge"]
dependencies = { jless = "*" }
exposed = { jless = "jless" }

[envs.file]
channels = ["conda-forge"]
dependencies = { file = "*" }
exposed = { file = "file" }

[envs.mergiraf]
channels = ["conda-forge"]
dependencies = { mergiraf = "*" }
exposed = { mergiraf = "mergiraf" }

[envs.just]
channels = ["conda-forge"]
dependencies = { just = "*" }
exposed = { just = "just" }

[envs.cmake]
channels = ["conda-forge"]
dependencies = { cmake = "*" }
exposed = { ccmake = "ccmake", cmake = "cmake", cpack = "cpack", ctest = "ctest" }

[envs.patchelf]
channels = ["conda-forge"]
dependencies = { patchelf = "*" }
exposed = { patchelf = "patchelf" }
